---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@e0c532a7b0fb264b3ff0c718c2c0308a0c8c1390 # main
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
